# Generated by Django 5.0.2 on 2024-02-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0002_matchlist_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchlist',
            old_name='is_active',
            new_name='finished',
        ),
    ]
