# Generated by Django 5.0.2 on 2024-02-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0003_rename_is_active_matchlist_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='progress',
            field=models.CharField(default='No started', max_length=20),
        ),
    ]
