# Generated by Django 5.0.2 on 2024-02-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0004_matchlist_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlist',
            name='progress',
            field=models.CharField(default='no active', max_length=20),
        ),
    ]
