# Generated by Django 5.0.2 on 2024-02-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0005_alter_matchlist_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchlist',
            old_name='finished',
            new_name='start_game',
        ),
    ]
