# Generated by Django 5.0.2 on 2024-02-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0006_rename_finished_matchlist_start_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
