# Generated by Django 5.0.2 on 2024-02-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0007_matchlist_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerslist',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
