# Generated by Django 5.0.2 on 2024-02-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0010_delete_englishdictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary', models.CharField(max_length=300)),
            ],
        ),
    ]
