# Generated by Django 5.0.2 on 2024-02-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0011_englishdictionary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnglishDictionary',
        ),
    ]
