# Generated by Django 5.0.2 on 2024-02-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0015_englishdictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerslist',
            name='start_game',
            field=models.BooleanField(default=False),
        ),
    ]
