# Generated by Django 5.0.2 on 2024-02-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0016_gamerslist_start_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerslist',
            name='chance',
            field=models.IntegerField(default=3),
        ),
    ]
