# Generated by Django 5.0.2 on 2024-02-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0019_alter_gamerslist_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerslist',
            name='queue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
