# Generated by Django 5.0.2 on 2024-02-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0021_alter_gamerslist_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='queue',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
