# Generated by Django 4.0.8 on 2024-02-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0022_matchlist_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerslist',
            name='progress',
            field=models.CharField(blank=True, default='no active', max_length=15, null=True),
        ),
    ]
