# Generated by Django 5.0.2 on 2024-02-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0024_alter_matchlist_players_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerslist',
            name='send_msg',
            field=models.BooleanField(default=False),
        ),
    ]
