# Generated by Django 5.0.2 on 2024-02-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0025_gamerslist_send_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='send_msg_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
