# Generated by Django 5.0.2 on 2024-02-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0026_matchlist_send_msg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlist',
            name='send_msg_id',
            field=models.CharField(blank=True, default='1', max_length=300, null=True),
        ),
    ]
