# Generated by Django 4.0.8 on 2024-03-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0028_alter_matchlist_send_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='gameinfo_msg_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
