# Generated by Django 5.0.2 on 2024-03-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0029_matchlist_gameinfo_msg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlist',
            name='send_msg_id',
            field=models.PositiveIntegerField(blank=True, max_length=280, null=True),
        ),
    ]
