# Generated by Django 5.0.2 on 2024-03-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0030_alter_matchlist_send_msg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlist',
            name='send_msg_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
