# Generated by Django 5.0.2 on 2024-03-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0031_alter_matchlist_send_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlist',
            name='founded_word',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='matchlist',
            name='last_latter',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
