# Generated by Django 5.0.2 on 2024-03-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordgame', '0032_matchlist_founded_word_matchlist_last_latter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlist',
            name='founded_word',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
